# 3 Business Owner Perspective

In this notebook, we will analyze the taxi data from the perspective of a business owner who is interested in establishing a retail outlet in New York City. The business owner wants to determine the optimal store location, ideally on a busy street that receives a lot of taxi traffic.

We will start with a bird's eye view of Manhattan, and examine general taxi traffic on a map that ranks the various taxi zones based on dropoffs. We will use this view to pick a general neighborhood.

Once we pick the general zone we want to be in, we will get down to the street level. We will construct a detailed street map with individual dropoffs plotted on it. 

Then, we will use machine learning to discover hotspots of activity. This will be achieved by applying a clustering algorithm (unsupervised machine learning) to Latitude and Longitude information contained in the data. The resulting clusters will become the short list of potential locations for the business owner's new store!

In [13]:
#The bird's eye view is constructed by using summarizing the data by dropoff zone, then visualizing it using QGIS
#We have already summarized the data by dropoff zone in Step 1, so we will pull in that information here.
import pandas as pd
df = pd.read_csv('../01_Tourist_Resident/01_Tourist_Resident.csv')
df

       ROWID               dropoff_zone do_weekday  do_hour  ridecount
0          0             Midtown Center  Wednesday      7.0      10075
1          1             Midtown Center   Thursday      7.0       9825
2          2             Midtown Center  Wednesday      8.0       9466
3          3             Midtown Center   Thursday      8.0       9289
4          4             Midtown Center  Wednesday      9.0       7932
5          5             Midtown Center    Tuesday      7.0       7920
6          6               Midtown East  Wednesday      8.0       7603
7          7             Midtown Center   Thursday      9.0       7515
8          8               Midtown East  Wednesday      7.0       7372
9          9             Midtown Center    Tuesday      8.0       7367
10        10               Midtown East   Thursday      8.0       7291
11        11             Midtown Center     Monday      7.0       7282
12        12             Midtown Center     Friday      8.0       7244
13        13             Midtown Center     Friday      7.0       7219
14        14               Midtown East   Thursday      7.0       7163
15        15             Midtown Center     Monday      8.0       6763
16        16  Times Sq/Theatre District     Friday     19.0       6142
17        17             Midtown Center    Tuesday      9.0       6130
18        18             Midtown Center  Wednesday     10.0       6098
19        19             Midtown Center     Friday      9.0       6018
20        20               Midtown East    Tuesday      8.0       5825
21        21               Midtown East    Tuesday      7.0       5820
22        22               Midtown East  Wednesday      9.0       5625
23        23             Midtown Center   Thursday     10.0       5612
24        24             Midtown Center  Wednesday     12.0       5496
25        25               Midtown East   Thursday      9.0       5491
26        26             Midtown Center     Monday      9.0       5476
27        27             Midtown Center  Wednesday     11.0       5459
28        28               Midtown East     Monday      7.0       5407
29        29               Midtown East     Friday      8.0       5385
...      ...                        ...        ...      ...        ...
39842  39842              Willets Point   Thursday      9.0          1
39843  39843              Willets Point   Thursday     12.0          1
39844  39844              Willets Point   Thursday     16.0          1
39845  39845              Willets Point   Thursday     17.0          1
39846  39846              Willets Point   Thursday     18.0          1
39847  39847              Willets Point   Thursday     19.0          1
39848  39848              Willets Point     Friday     12.0          1
39849  39849              Willets Point     Friday     14.0          1
39850  39850              Willets Point     Friday     19.0          1
39851  39851              Willets Point     Friday     22.0          1
39852  39852              Willets Point   Saturday      2.0          1
39853  39853              Willets Point   Saturday     22.0          1
39854  39854   Williamsbridge/Olinville     Sunday      8.0          1
39855  39855   Williamsbridge/Olinville     Monday      4.0          1
39856  39856   Williamsbridge/Olinville    Tuesday      4.0          1
39857  39857   Williamsbridge/Olinville    Tuesday      8.0          1
39858  39858   Williamsbridge/Olinville    Tuesday     15.0          1
39859  39859   Williamsbridge/Olinville  Wednesday      6.0          1
39860  39860   Williamsbridge/Olinville  Wednesday     10.0          1
39861  39861   Williamsbridge/Olinville   Thursday      9.0          1
39862  39862   Williamsbridge/Olinville     Friday      8.0          1
39863  39863   Williamsbridge/Olinville     Friday     17.0          1
39864  39864         Woodlawn/Wakefield     Monday      9.0          1
39865  39865         Woodlawn/Wakefield    Tuesday     10.0          1
39866  39866         Woodlawn/Wakefield  Wednesday      6.0          1
39867  39867         Woodlawn/Wakefield   Thursday      8.0          1
39868  39868         Woodlawn/Wakefield     Friday      9.0          1
39869  39869         Woodlawn/Wakefield   Saturday      8.0          1
39870  39870         Woodlawn/Wakefield   Saturday      9.0          1
39871  39871                     zone_1        NaN      NaN          1

[39872 rows x 5 columns]

In [14]:
import numpy as np
summary = pd.pivot_table(df, values='ridecount', index=['dropoff_zone'],aggfunc=np.sum)

In [17]:
summary.sort_values(ascending=False)

dropoff_zone
Midtown Center                                   456367
Times Sq/Theatre District                        385849
Murray Hill                                      381494
Midtown East                                     376738
Penn Station/Madison Sq West                     339835
Upper East Side South                            334615
Union Sq                                         332632
Upper East Side North                            330459
Clinton East                                     314599
East Village                                     300551
Midtown North                                    288713
Midtown South                                    268810
East Chelsea                                     268013
Lincoln Square East                              263386
Gramercy                                         245290
Lenox Hill West                                  242337
Upper West Side South                            237176
West Chelsea/Hudson Yards                        223234
TriBeCa/Civic Center                             204429
West Village                                     193484
Garment District                                 191947
Lenox Hill East                                  189348
Yorkville West                                   188133
Sutton Place/Turtle Bay North                    185979
Upper West Side North                            183976
UN/Turtle Bay South                              171774
Flatiron                                         166013
Greenwich Village North                          161851
Meatpacking/West Village West                    156353
Kips Bay                                         154943
                                                  ...
Heartland Village/Todt Hill                         229
Saint George/New Brighton                           208
Arrochar/Fort Wadsworth                             194
Stapleton                                           187
South Beach/Dongan Hills                            175
Westerleigh                                         164
City Island                                         163
Green-Wood Cemetery                                 162
Pelham Bay Park                                     147
Grymes Hill/Clifton                                 144
Breezy Point/Fort Tilden/Riis Beach                 140
West Brighton                                       139
Marine Park/Floyd Bennett Field                     123
New Dorp/Midland Beach                              114
Great Kills                                         112
Willets Point                                        99
Mariners Harbor                                      92
Crotona Park                                         81
Oakwood                                              79
Eltingville/Annadale/Prince's Bay                    70
Arden Heights                                        57
Rossville/Woodrow                                    55
Port Richmond                                        41
Charleston/Tottenville                               40
Broad Channel                                        39
Governor's Island/Ellis Island/Liberty Island         6
Jamaica Bay                                           5
Freshkills Park                                       2
Rikers Island                                         1
zone_1                                                1
Name: ridecount, dtype: int64

In [28]:
zone_summary = pd.DataFrame(summary,index=summary.count)

TypeError: 'method' object is not iterable

In [26]:
?pd.DataFrame

In [27]:
np.arange(5)

array([0, 1, 2, 3, 4])